export const urlServer = 'http://127.0.0.1:8000'
export const uriReport = '/api/report/'
export const uriReportCsrf = '/api/report/csrf/'
export const uriHasAccess = '/api/has-access/'
export const uriLogout = '/api/logout/'
export const uriLogin = '/api/login/'
export const uriTranslationFr = '/api/translation/fr/'
export const uriGetUser = '/api/get-user/'
export const uriVotes = '/api/votes/'
export const uriCSRF = '/api/csrf/'

export const uriReportForm = '/api/report-form/'
