# Generated by Django 3.2.9 on 2022-03-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='creator',
            new_name='owner',
        ),
    ]
