# Generated by Django 3.2.9 on 2022-03-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
