# Generated by Django 3.2.9 on 2021-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category_1',
            field=models.IntegerField(choices=[(0, 'NONE_CAT_1'), (1, 'INFRASTRUCTURE'), (2, 'INCIDENT')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='category_2',
            field=models.IntegerField(choices=[(0, 'NONE_CAT_2'), (1, 'BICYCLE_PATH_HOLE'), (2, 'BICYCLE_PATH_POOR_CONDITION'), (3, 'BICYCLE_PATH_VANISHED_PAINT'), (4, 'BICYCLE_PATH_UNCLEAR_SIGNAGE'), (5, 'BICYCLE_PATH_BORDER_NEED_TO_BE_LOWERED'), (6, 'NO_BICYCLE_PATH_DANGEROUS_SITUATION'), (7, 'SIGNAGE__MISSING'), (8, 'SIGNAGE__BAD_CONDITION')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'NONE_USER_TYPE'), (1, 'PEDESTRIAN'), (2, 'CYCLIST')]),
        ),
    ]
