# Generated by Django 3.2.9 on 2022-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
