# Generated by Django 3.2.9 on 2022-04-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='operation',
            field=models.IntegerField(choices=[(0, 'NONE_OPERATION'), (1, 'LOCALE')], default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reportimage'),
        ),
    ]
