# Generated by Django 3.2.9 on 2021-12-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_votes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together={('user', 'report')},
        ),
    ]
