# Generated by Django 3.2.9 on 2022-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220401_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category_2',
            field=models.IntegerField(choices=[(0, 'NONE_CAT_2'), (1, 'LANE_HOLE'), (2, 'LANE_POOR_CONDITION'), (3, 'LANE_VANISHED_PAINT'), (4, 'LANE_UNCLEAR_SIGNAGE'), (5, 'LANE_BORDER_NEED_TO_BE_LOWERED'), (6, 'LANE_SLIPPERY'), (7, 'LANE_TOO_THIN'), (8, 'LANE_CROSSING_DANGEROUS'), (9, 'LANE_PRIORITY_NOT_RESPECTED_DANGEROUS'), (10, 'LANE_CROSSWALK_MISSING'), (11, 'RACK_DAMAGED'), (12, 'NO_BICYCLE_PATH_DANGEROUS_SITUATION'), (13, 'SIGNAGE__MISSING'), (14, 'SIGNAGE__BAD_CONDITION'), (15, 'INCIDENT_GLASS_ON_LANE'), (16, 'INCIDENT_NAILS_ON_LANE'), (17, 'ILLEGAL_PARKING')]),
        ),
    ]
