# Generated by Django 3.2.9 on 2022-04-07 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_report_category_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAnnotationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_charge', models.SmallIntegerField(choices=[(0, 'IN_CHARGE_NONE'), (1, 'MUNICIPALITY'), (2, 'REGION')], default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'STATUS_NONE'), (1, 'REPORTED'), (2, 'CLASSIFIED'), (3, 'REPORTED_TO_AUTHORITIES'), (4, 'NOT_RELEVANT'), (5, 'REPORT_IN_PROGRESS'), (6, 'SOLVED')], default=1)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.area')),
                ('comments', models.ManyToManyField(blank=True, to='api.ReportAnnotationComment')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='annotation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reportannotation'),
        ),
    ]
