# Generated by Django 3.2.9 on 2022-01-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211231_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='urgent',
        ),
    ]
