# Generated by Django 3.2.9 on 2022-04-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220407_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coordinator_area',
            field=models.ManyToManyField(default=None, to='api.Area'),
        ),
    ]
