# Generated by Django 3.2.9 on 2022-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220414_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='area',
            name='boundary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
