# Generated by Django 3.2.9 on 2022-05-01 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_load_communes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='alias',
            field=models.CharField(default='Anonymous', max_length=20, verbose_name='pseudo'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.ManyToManyField(blank=True, default=None, to='api.Notifications'),
        ),
    ]
