# Generated by Django 3.2.9 on 2022-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.JSONField(blank=True, default=list)),
                ('timestamp_creation', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modification', models.DateTimeField(auto_now=True)),
                ('owner', models.ManyToManyField(blank=True, default=None, to='api.Area')),
                ('reports', models.ManyToManyField(blank=True, default=None, to='api.Report')),
            ],
        ),
    ]
